import 'package:flutter/material.dart';
import 'package:flutterapp/cover_beautyapp/generatedregistrowidget/generated/GeneratedInputFieldWidget4.dart';
import 'package:flutterapp/cover_beautyapp/generatedregistrowidget/generated/GeneratedInputFieldWidget7.dart';
import 'package:flutterapp/cover_beautyapp/generatedregistrowidget/generated/GeneratedCheckboxWidget.dart';
import 'package:flutterapp/cover_beautyapp/generatedregistrowidget/generated/GeneratedLightActiveWidget1.dart';
import 'package:flutterapp/cover_beautyapp/generatedregistrowidget/generated/GeneratedInputFieldWidget6.dart';
import 'package:flutterapp/cover_beautyapp/generatedregistrowidget/generated/GeneratedInputFieldWidget5.dart';
import 'package:flutterapp/cover_beautyapp/generatedregistrowidget/generated/GeneratedFrame31Widget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/cover_beautyapp/generatedregistrowidget/generated/GeneratedLightInactiveWidget1.dart';
import 'package:flutterapp/cover_beautyapp/generatedregistrowidget/generated/GeneratedSegmentedControls3SegmentsWidget.dart';

/* Frame Registro
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegistroWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 375.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 127, 221, 94),
                ),
              ),
              Positioned(
                left: 22.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 335.0,
                height: 80.0,
                child: GeneratedInputFieldWidget4(),
              ),
              Positioned(
                left: 26.0,
                top: 197.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 80.0,
                child: GeneratedInputFieldWidget5(),
              ),
              Positioned(
                left: 25.0,
                top: 297.0,
                right: null,
                bottom: null,
                width: 332.0,
                height: 80.0,
                child: GeneratedInputFieldWidget6(),
              ),
              Positioned(
                left: 19.0,
                top: 386.0,
                right: null,
                bottom: null,
                width: 332.0,
                height: 80.0,
                child: GeneratedInputFieldWidget7(),
              ),
              Positioned(
                left: 18.0,
                top: 526.0,
                right: null,
                bottom: null,
                width: 332.0,
                height: 45.0,
                child: GeneratedFrame31Widget3(),
              ),
              Positioned(
                left: 25.0,
                top: 497.0,
                right: null,
                bottom: null,
                width: 252.0,
                height: 20.0,
                child: GeneratedCheckboxWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 332.0,
                height: 29.0,
                child: GeneratedSegmentedControls3SegmentsWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 53.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 48.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.44533333333333336;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06666666666666667,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedLightInactiveWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 53.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 50.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.424;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5093333333333333,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedLightActiveWidget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
