import 'package:flutter/material.dart';
import 'package:flutterapp/cover_beautyapp/generatedactivityusuariowidget/generated/GeneratedAppNavigationWidget.dart';
import 'package:flutterapp/cover_beautyapp/generatedactivityusuariowidget/generated/GeneratedLightInactiveWidget2.dart';
import 'package:flutterapp/cover_beautyapp/generatedactivityusuariowidget/generated/GeneratedRoundIconWidget3.dart';
import 'package:flutterapp/cover_beautyapp/generatedactivityusuariowidget/generated/GeneratedPlusMathWidget.dart';
import 'package:flutterapp/cover_beautyapp/generatedactivityusuariowidget/generated/GeneratedRoundIconWidget1.dart';
import 'package:flutterapp/cover_beautyapp/generatedactivityusuariowidget/generated/GeneratedRoundIconWidget5.dart';
import 'package:flutterapp/cover_beautyapp/generatedactivityusuariowidget/generated/GeneratedRoundIconWidget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/cover_beautyapp/generatedactivityusuariowidget/generated/GeneratedLightHamburgerWidget.dart';
import 'package:flutterapp/cover_beautyapp/generatedactivityusuariowidget/generated/GeneratedLightActiveWidget2.dart';
import 'package:flutterapp/cover_beautyapp/generatedactivityusuariowidget/generated/GeneratedRoundIconWidget.dart';
import 'package:flutterapp/cover_beautyapp/generatedactivityusuariowidget/generated/GeneratedDarkWidget.dart';
import 'package:flutterapp/cover_beautyapp/generatedactivityusuariowidget/generated/GeneratedBrightnessWidget.dart';
import 'package:flutterapp/cover_beautyapp/generatedactivityusuariowidget/generated/GeneratedRoundIconWidget2.dart';

/* Component Activity/Usuario
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedActivityUsuarioWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 375.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 120.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 80.0,
                child: GeneratedRoundIconWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 336.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 64.0,
                child: GeneratedRoundIconWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 202.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 64.0,
                child: GeneratedRoundIconWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 268.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 64.0,
                child: GeneratedRoundIconWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 400.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 80.0,
                child: GeneratedRoundIconWidget4(),
              ),
              Positioned(
                left: 0.0,
                top: 482.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 64.0,
                child: GeneratedRoundIconWidget5(),
              ),
              Positioned(
                left: 1.0,
                top: 9.0,
                right: -1.0,
                bottom: null,
                width: null,
                height: 56.0,
                child: GeneratedLightHamburgerWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 56.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 48.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.5;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedLightInactiveWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 57.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 48.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.432;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.504,
                        y: 0,
                        z: 0,
                        child: Container(
                          width: width,
                          child: GeneratedLightActiveWidget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: null,
                top: null,
                right: 28.0,
                bottom: 76.0,
                width: 56.0,
                height: 56.0,
                child: GeneratedDarkWidget(),
              ),
              Positioned(
                left: 311.0,
                top: 22.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 30.0,
                child: GeneratedBrightnessWidget(),
              ),
              Positioned(
                left: 299.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 40.0,
                height: 34.0,
                child: GeneratedPlusMathWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 566.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 71.0,
                child: GeneratedAppNavigationWidget(),
              )
            ]),
      ),
    ));
  }
}
