import 'package:flutter/material.dart';
import 'package:flutterapp/cover_beautyapp/generatedstartwidget/generated/GeneratedLoginWidget1.dart';
import 'package:flutterapp/cover_beautyapp/generatedstartwidget/generated/GeneratedFrame48Widget.dart';
import 'package:flutterapp/cover_beautyapp/generatedstartwidget/generated/GeneratedFrame31Widget.dart';
import 'package:flutterapp/cover_beautyapp/generatedstartwidget/generated/GeneratedFrame41Widget.dart';

/* Frame Start
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStartWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: Container(
        width: 360.0,
        height: 640.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(20.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(20.0),
                child: Container(
                  color: Color.fromARGB(255, 126, 221, 93),
                ),
              ),
              Positioned(
                left: 81.0,
                top: 147.0,
                right: null,
                bottom: null,
                width: 198.0,
                height: 134.0,
                child: GeneratedFrame48Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 45.0,
                child: GeneratedFrame31Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 362.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 45.0,
                child: GeneratedFrame41Widget(),
              ),
              Positioned(
                left: 360.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedLoginWidget1(),
              )
            ]),
      ),
    ));
  }
}
